include_guard(GLOBAL)

if(NOT WIN32)
    message(WARNING "AiDA C03 dependencies are Windows-only")
endif()

cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH AIDA_C03_DEPENDENCY_ROOT)
set(AIDA_C03_MANAGED_WORKER_ROOT "${AIDA_C03_DEPENDENCY_ROOT}/src/standalone/workers/managed_decompiler")
set(AIDA_C03_MANAGED_WORKER_PROJECT "${AIDA_C03_MANAGED_WORKER_ROOT}/ManagedDecompilerWorker.csproj")
set(AIDA_C03_MANAGED_WORKER_NUGET_CONFIG "${AIDA_C03_MANAGED_WORKER_ROOT}/NuGet.Config")
set(AIDA_C03_DOTNET_EXECUTABLE "${AIDA_C03_DEPENDENCY_ROOT}/.deps/dotnet-sdk-10.0.301-win-x64/dotnet.exe")
if(NOT EXISTS "${AIDA_C03_DOTNET_EXECUTABLE}")
    find_program(_aida_system_dotnet dotnet PATHS "C:/Program Files/dotnet" "C:/Program Files (x86)/dotnet" NO_DEFAULT_PATH)
    if(_aida_system_dotnet AND EXISTS "${_aida_system_dotnet}")
        set(AIDA_C03_DOTNET_EXECUTABLE "${_aida_system_dotnet}")
    else()
        find_program(_aida_system_dotnet2 dotnet)
        if(_aida_system_dotnet2)
            set(AIDA_C03_DOTNET_EXECUTABLE "${_aida_system_dotnet2}")
        endif()
    endif()
endif()
set(AIDA_C03_MANAGED_APPHOST_SOURCE "${AIDA_C03_DEPENDENCY_ROOT}/.deps/dotnet-sdk-10.0.301-win-x64/packs/Microsoft.NETCore.App.Host.win-x64/10.0.9/runtimes/win-x64/native/apphost.exe")
if(NOT EXISTS "${AIDA_C03_MANAGED_APPHOST_SOURCE}" AND EXISTS "${AIDA_C03_DOTNET_EXECUTABLE}")
    get_filename_component(_aida_dotnet_root "${AIDA_C03_DOTNET_EXECUTABLE}" DIRECTORY)
    file(GLOB _aida_apphost_candidates "${_aida_dotnet_root}/packs/Microsoft.NETCore.App.Host.win-x64/*/runtimes/win-x64/native/apphost.exe")
    if(_aida_apphost_candidates)
        list(SORT _aida_apphost_candidates COMPARE NATURAL ORDER DESCENDING)
        list(GET _aida_apphost_candidates 0 AIDA_C03_MANAGED_APPHOST_SOURCE)
    else()
        set(AIDA_C03_MANAGED_APPHOST_SOURCE "${AIDA_C03_DOTNET_EXECUTABLE}")
    endif()
endif()

function(aida_c03_register_pcre2_8bit_no_jit)
    if(TARGET pcre2-8)
        if(NOT TARGET pcre2-8-static)
            message(WARNING "AiDA C03 PCRE2 dependency is not the approved static 8-bit target")
        endif()
        return()
    endif()
    set(_aida_c03_pcre2_source "${AIDA_C03_DEPENDENCY_ROOT}/.deps/pcre2-10.47")
    set(_aida_c03_pcre2_binary "${CMAKE_BINARY_DIR}/.deps/pcre2-c03")
    if(NOT EXISTS "${_aida_c03_pcre2_source}/CMakeLists.txt" OR IS_DIRECTORY "${_aida_c03_pcre2_source}/CMakeLists.txt")
        message(WARNING "AiDA C03 PCRE2 dependency is missing: CMakeLists.txt")
    endif()
    if(NOT EXISTS "${_aida_c03_pcre2_source}/src/pcre2.h.generic" OR IS_DIRECTORY "${_aida_c03_pcre2_source}/src/pcre2.h.generic")
        message(WARNING "AiDA C03 PCRE2 dependency is missing: src/pcre2.h.generic")
    endif()
    if(NOT EXISTS "${_aida_c03_pcre2_source}/LICENCE.md" OR IS_DIRECTORY "${_aida_c03_pcre2_source}/LICENCE.md")
        message(WARNING "AiDA C03 PCRE2 dependency is missing: LICENCE.md")
    endif()
    set(_aida_c03_saved_build_shared_libs "${BUILD_SHARED_LIBS}")
    set(_aida_c03_saved_build_static_libs "${BUILD_STATIC_LIBS}")
    set(BUILD_SHARED_LIBS OFF)
    set(BUILD_STATIC_LIBS ON)
    set(PCRE2_BUILD_PCRE2_8 ON CACHE BOOL "" FORCE)
    set(PCRE2_BUILD_PCRE2_16 OFF CACHE BOOL "" FORCE)
    set(PCRE2_BUILD_PCRE2_32 OFF CACHE BOOL "" FORCE)
    set(PCRE2_BUILD_PCRE2GREP OFF CACHE BOOL "" FORCE)
    set(PCRE2_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(PCRE2_SUPPORT_JIT OFF CACHE BOOL "" FORCE)
    set(PCRE2_SUPPORT_JIT_SEALLOC OFF CACHE BOOL "" FORCE)
    add_subdirectory("${_aida_c03_pcre2_source}" "${_aida_c03_pcre2_binary}" EXCLUDE_FROM_ALL)
    set(BUILD_SHARED_LIBS "${_aida_c03_saved_build_shared_libs}")
    set(BUILD_STATIC_LIBS "${_aida_c03_saved_build_static_libs}")
    if(NOT TARGET pcre2-8 OR NOT TARGET pcre2-8-static)
        message(WARNING "AiDA C03 PCRE2 static 8-bit target registration failed")
    endif()
    set_target_properties(pcre2-8-static PROPERTIES FOLDER "Dependencies/C03")
endfunction()

aida_c03_register_pcre2_8bit_no_jit()
